#!/usr/bin/env bash

if [[ "$#" -eq 0 ]]; then
   echo "usage: $(basename '$0') [app path]"
   echo "disable Gatekeeper protection for a given application"
   echo
   exit 0
fi

if [[ $EUID -ne 0 ]]; then
   echo "macfree must be run as root!"
   echo
   exit 1
fi

xattr -dr com.apple.quarantine $1
