.Dd 11/19/2025
.Dt macfree 1
.Os
.Sh NAME
.Nm macfree
.Nd disable Gatekeeper protection for a given macOS application
.Sh SYNOPSIS
.Nm
.Op Ar application/binary
.Sh DESCRIPTION
macOS automatically disables the execution of unsigned applications and
binaries through the Gatekeeper protocol - macfree disables this for
ONLY the application/binary provided, using the built-in
.Nm xattr
command.
.El
.Sh SEE ALSO
.Xr xattr 1
